RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium fonts-liberation libnss3 libatk-bridge2.0-0 libxkbcommon0 \
    libgbm1 libasound2 \
 && rm -rf /var/lib/apt/lists/*
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV BROWSERSHOT_CHROME_PATH=/usr/bin/chromium
